import mods.modularmachinery.RecipeBuilder;
import mods.modularmachinery.RecipePrimer;
import crafttweaker.item.IItemStack;

var m = "primal_furnace";

// This thing processes ores extremely fast
// ffs zenscript just let me do this in a less bad way
// I had to write an external python script for this
mods.modularmachinery.RecipeBuilder.newBuilder('processrutile', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<libvulpes:productingot:7> * 192).addItemInput(<libvulpes:ore0:8> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processdilithium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<libvulpes:productgem:0> * 192).addItemInput(<libvulpes:ore0:0> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processcoal', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:coal> * 256).addItemInput(<minecraft:coal_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processbiotite', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<quark:biotite> * 256).addItemInput(<quark:biotite_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processiron', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:iron_ingot> * 192).addItemInput(<minecraft:iron_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processquartz', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:quartz> * 384).addItemInput(<minecraft:quartz_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processredstone', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:redstone> * 768).addItemInput(<minecraft:redstone_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processlapis', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:dye:4> * 768).addItemInput(<minecraft:lapis_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processgold', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:gold_ingot> * 192).addItemInput(<minecraft:gold_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processdiamond', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:diamond> * 192).addItemInput(<minecraft:diamond_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processemerald', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:emerald> * 192).addItemInput(<minecraft:emerald_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processcopper', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:128> * 192).addItemInput(<thermalfoundation:ore:0> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processtin', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:129> * 192).addItemInput(<thermalfoundation:ore:1> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processsilver', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:130> * 192).addItemInput(<thermalfoundation:ore:2> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processlead', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:131> * 192).addItemInput(<thermalfoundation:ore:3> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processaluminum', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:132> * 192).addItemInput(<thermalfoundation:ore:4> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processuranium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:ingot:4> * 192).addItemInput(<nuclearcraft:ore:4> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processcertus', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<appliedenergistics2:material:0> * 256).addItemInput(<appliedenergistics2:quartz_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processchargedcertus', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<appliedenergistics2:material:1> * 256).addItemInput(<appliedenergistics2:charged_quartz_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processnickel', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:133> * 192).addItemInput(<thermalfoundation:ore:5> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processplatinum', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:134> * 192).addItemInput(<thermalfoundation:ore:6> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processmithril', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:136> * 192).addItemInput(<thermalfoundation:ore:8> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processresonant', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:ender_pearl> * 256).addItemInput(<thermalfoundation:ore_fluid:4> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processglowing', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:glowstone_dust> * 256).addItemInput(<thermalfoundation:ore_fluid:3> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processgeode', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:1028> * 256).addItemInput(<thermalfoundation:geode> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processunstable', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<minecraft:redstone> * 640).addItemInput(<thermalfoundation:ore_fluid:2> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processcobalt', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<contenttweaker:cobalt_ingot> * 192).addItemInput(<contenttweaker:cobalt_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processardite', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<contenttweaker:ardite_ingot> * 192).addItemInput(<contenttweaker:ardite_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processblackquartz', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<actuallyadditions:item_misc:5> * 192).addItemInput(<actuallyadditions:block_misc:3> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processmagnesium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:ingot:7> * 192).addItemInput(<nuclearcraft:ore:7> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processlithium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:ingot:6> * 192).addItemInput(<nuclearcraft:ore:6> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processthorium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:ingot:3> * 192).addItemInput(<nuclearcraft:ore:3> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processboron', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:ingot:5> * 192).addItemInput(<nuclearcraft:ore:5> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processiridium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<thermalfoundation:material:135> * 192).addItemInput(<thermalfoundation:ore:7> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processtungsten', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<contenttweaker:tungsten_ingot> * 192).addItemInput(<contenttweaker:tungsten_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processadamantium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<contenttweaker:adamantium_ingot> * 192).addItemInput(<contenttweaker:adamantium_ore> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processosmium', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<mekanism:ingot:1> * 192).addItemInput(<mekanism:oreblock:0> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processdimshard', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<rftools:dimensional_shard> * 192).addItemInput(<rftools:dimensional_shard_ore:0> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processelectrotine', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<projectred-core:resource_item:105> * 512).addItemInput(<projectred-exploration:ore:6> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processruby', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<projectred-core:resource_item:200> * 192).addItemInput(<projectred-exploration:ore:0> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processperidot', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<projectred-core:resource_item:202> * 192).addItemInput(<projectred-exploration:ore:2> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder('processsapphire', 'primal_furnace', 1).addEnergyPerTickInput(1000000).addItemOutput(<projectred-core:resource_item:201> * 192).addItemInput(<projectred-exploration:ore:1> * 64).addFluidInput(<liquid:mana> * 40).build();

// U235 recipes for fast molybdenum
mods.modularmachinery.RecipeBuilder.newBuilder("u235process", "primal_furnace", 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:depleted_fuel_uranium:11> * 64).addItemInput(<nuclearcraft:fuel_uranium:11> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder("u235process2", "primal_furnace", 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:depleted_fuel_uranium:9> * 64).addItemInput(<nuclearcraft:fuel_uranium:9> * 64).addFluidInput(<liquid:mana> * 40).build();
mods.modularmachinery.RecipeBuilder.newBuilder("u235process3", "primal_furnace", 1).addEnergyPerTickInput(1000000).addItemOutput(<nuclearcraft:depleted_fuel_uranium:10> * 64).addItemInput(<nuclearcraft:fuel_uranium:10> * 64).addFluidInput(<liquid:mana> * 40).build();